# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'certificates.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(562, 378)
        Dialog.setStyleSheet("QToolTip\n"
                             "{\n"
                             "     border: 1px solid black;\n"
                             "     background-color: #D1DBCB;\n"
                             "     padding: 1px;\n"
                             "     border-radius: 3px;\n"
                             "     opacity: 100;\n"
                             "}\n"
                             "\n"
                             "QWidget\n"
                             "{\n"
                             "    color: #b1b1b1;\n"
                             "    background-color: #323232;\n"
                             "}\n"
                             "\n"
                             "QWidget:item:hover\n"
                             "{\n"
                             "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #D1DBCB, stop: 1 #b2b6af);\n"
                             "    color: #000000;\n"
                             "}\n"
                             "\n"
                             "QWidget:item:selected\n"
                             "{\n"
                             "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #D1DBCB, stop: 1 #b2b6af);\n"
                             "}\n"
                             "\n"
                             "QMenuBar::item\n"
                             "{\n"
                             "    background: transparent;\n"
                             "}\n"
                             "\n"
                             "QMenuBar::item:selected\n"
                             "{\n"
                             "    background: transparent;\n"
                             "    border: 1px solid #fdf6e3;\n"
                             "}\n"
                             "\n"
                             "QMenuBar::item:pressed\n"
                             "{\n"
                             "    background: #444;\n"
                             "    border: 1px solid #000;\n"
                             "    background-color: QLinearGradient(\n"
                             "        x1:0, y1:0,\n"
                             "        x2:0, y2:1,\n"
                             "        stop:1 #212121,\n"
                             "        stop:0.4 #343434/*,\n"
                             "        stop:0.2 #343434,\n"
                             "        stop:0.1 #fdf6e3*/\n"
                             "    );\n"
                             "    margin-bottom:-1px;\n"
                             "    padding-bottom:1px;\n"
                             "}\n"
                             "\n"
                             "QMenu\n"
                             "{\n"
                             "    border: 1px solid #000;\n"
                             "}\n"
                             "\n"
                             "QMenu::item\n"
                             "{\n"
                             "    padding: 2px 20px 2px 20px;\n"
                             "}\n"
                             "\n"
                             "QMenu::item:selected\n"
                             "{\n"
                             "    color: #000000;\n"
                             "}\n"
                             "\n"
                             "QWidget:disabled\n"
                             "{\n"
                             "    color: #404040;\n"
                             "    background-color: #323232;\n"
                             "}\n"
                             "\n"
                             "QAbstractItemView\n"
                             "{\n"
                             "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0.1 #646464, stop: 1 #5d5d5d);\n"
                             "}\n"
                             "\n"
                             "QWidget:focus\n"
                             "{\n"
                             "    /*border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0\n"
                             "     #D1DBCB, stop: 1 #b2b6af);*/\n"
                             "}\n"
                             "\n"
                             "QLineEdit\n"
                             "{\n"
                             "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
                             "    padding: 1px;\n"
                             "    border-style: solid;\n"
                             "    border: 1px solid #1e1e1e;\n"
                             "    border-radius: 5;\n"
                             "}\n"
                             "\n"
                             "QPushButton\n"
                             "{\n"
                             "    color: #b1b1b1;\n"
                             "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
                             "    border-width: 1px;\n"
                             "    border-color: #1e1e1e;\n"
                             "    border-style: solid;\n"
                             "    border-radius: 6;\n"
                             "    padding: 3px;\n"
                             "    font-size: 12px;\n"
                             "    padding-left: 5px;\n"
                             "    padding-right: 5px;\n"
                             "}\n"
                             "\n"
                             "QPushButton:pressed\n"
                             "{\n"
                             "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
                             "}\n"
                             "\n"
                             "QComboBox\n"
                             "{\n"
                             "    selection-background-color: #fdf6e3;\n"
                             "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
                             "    border-style: solid;\n"
                             "    border: 1px solid #1e1e1e;\n"
                             "    border-radius: 5;\n"
                             "}\n"
                             "\n"
                             "QComboBox:hover,QPushButton:hover\n"
                             "{\n"
                             "    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0\n"
                             "    #D1DBCB, stop: 1 #b2b6af);\n"
                             "}\n"
                             "\n"
                             "\n"
                             "QComboBox:on\n"
                             "{\n"
                             "    padding-top: 3px;\n"
                             "    padding-left: 4px;\n"
                             "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
                             "    selection-background-color: #fdf6e3;\n"
                             "}\n"
                             "\n"
                             "QComboBox QAbstractItemView\n"
                             "{\n"
                             "    border: 2px solid darkgray;\n"
                             "    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
                             "     stop: 0 #D1DBCB, stop: 1 #b2b6af);\n"
                             "}\n"
                             "\n"
                             "QComboBox::drop-down\n"
                             "{\n"
                             "     subcontrol-origin: padding;\n"
                             "     subcontrol-position: top right;\n"
                             "     width: 15px;\n"
                             "\n"
                             "     border-left-width: 0px;\n"
                             "     border-left-color: darkgray;\n"
                             "     border-left-style: solid; /* just a single line */\n"
                             "     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
                             "     border-bottom-right-radius: 3px;\n"
                             " }\n"
                             "\n"
                             "QComboBox::down-arrow\n"
                             "{\n"
                             "     image: url(:/down_arrow.png);\n"
                             "}\n"
                             "\n"
                             "QGroupBox:focus\n"
                             "{\n"
                             "border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0\n"
                             "#D1DBCB, stop: 1 #b2b6af);\n"
                             "}\n"
                             "\n"
                             "QTextEdit:focus\n"
                             "{\n"
                             "    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0\n"
                             "    #D1DBCB, stop: 1 #b2b6af);\n"
                             "}\n"
                             "\n"
                             "QScrollArea:focus {\n"
                             "border: 1px solid black;\n"
                             "}\n"
                             "\n"
                             "QScrollBar:horizontal {\n"
                             "     border: 1px solid #222222;\n"
                             "     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
                             "     height: 7px;\n"
                             "     margin: 0px 16px 0 16px;\n"
                             "}\n"
                             "\n"
                             "QScrollBar::handle:horizontal\n"
                             "{\n"
                             "      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0\n"
                             "      #D1DBCB, stop: 0.5 #b2b6af, stop: 1 #D1DBCB);\n"
                             "      min-height: 20px;\n"
                             "      border-radius: 2px;\n"
                             "}\n"
                             "\n"
                             "QScrollBar::add-line:horizontal {\n"
                             "      border: 1px solid #1b1b19;\n"
                             "      border-radius: 2px;\n"
                             "      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0\n"
                             "      #D1DBCB, stop: 1 #b2b6af);\n"
                             "      width: 14px;\n"
                             "      subcontrol-position: right;\n"
                             "      subcontrol-origin: margin;\n"
                             "}\n"
                             "\n"
                             "QScrollBar::sub-line:horizontal {\n"
                             "      border: 1px solid #1b1b19;\n"
                             "      border-radius: 2px;\n"
                             "      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0\n"
                             "      #D1DBCB, stop: 1 #b2b6af);\n"
                             "      width: 14px;\n"
                             "     subcontrol-position: left;\n"
                             "     subcontrol-origin: margin;\n"
                             "}\n"
                             "\n"
                             "QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
                             "{\n"
                             "      border: 1px solid black;\n"
                             "      width: 1px;\n"
                             "      height: 1px;\n"
                             "      background: white;\n"
                             "}\n"
                             "\n"
                             "QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
                             "{\n"
                             "      background: none;\n"
                             "}\n"
                             "\n"
                             "QScrollBar:vertical\n"
                             "{\n"
                             "      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
                             "      width: 7px;\n"
                             "      margin: 16px 0 16px 0;\n"
                             "      border: 1px solid #222222;\n"
                             "}\n"
                             "\n"
                             "QScrollBar::handle:vertical\n"
                             "{\n"
                             "      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0\n"
                             "      #D1DBCB, stop: 0.5 #b2b6af, stop: 1 #D1DBCB);\n"
                             "      min-height: 20px;\n"
                             "      border-radius: 2px;\n"
                             "}\n"
                             "\n"
                             "QScrollBar::add-line:vertical\n"
                             "{\n"
                             "      border: 1px solid #1b1b19;\n"
                             "      border-radius: 2px;\n"
                             "      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0\n"
                             "      #D1DBCB, stop: 1 #b2b6af);\n"
                             "      height: 14px;\n"
                             "      subcontrol-position: bottom;\n"
                             "      subcontrol-origin: margin;\n"
                             "}\n"
                             "\n"
                             "QScrollBar::sub-line:vertical\n"
                             "{\n"
                             "      border: 1px solid #1b1b19;\n"
                             "      border-radius: 2px;\n"
                             "      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #b2b6af,\n"
                             "      stop: 1 #D1DBCB);\n"
                             "      height: 14px;\n"
                             "      subcontrol-position: top;\n"
                             "      subcontrol-origin: margin;\n"
                             "}\n"
                             "\n"
                             "QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
                             "{\n"
                             "      border: 1px solid black;\n"
                             "      width: 1px;\n"
                             "      height: 1px;\n"
                             "      background: white;\n"
                             "}\n"
                             "\n"
                             "\n"
                             "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
                             "{\n"
                             "      background: none;\n"
                             "}\n"
                             "\n"
                             "QTextEdit\n"
                             "{\n"
                             "    background-color: #242424;\n"
                             "}\n"
                             "\n"
                             "QPlainTextEdit\n"
                             "{\n"
                             "    background-color: #242424;\n"
                             "}\n"
                             "\n"
                             "QHeaderView::section\n"
                             "{\n"
                             "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);\n"
                             "    color: white;\n"
                             "    padding-left: 4px;\n"
                             "    border: 1px solid #6c6c6c;\n"
                             "}\n"
                             "\n"
                             "QCheckBox:disabled\n"
                             "{\n"
                             "color: #414141;\n"
                             "}\n"
                             "\n"
                             "QDockWidget::title\n"
                             "{\n"
                             "    text-align: center;\n"
                             "    spacing: 3px; /* spacing between items in the tool bar */\n"
                             "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
                             "}\n"
                             "\n"
                             "QDockWidget::close-button, QDockWidget::float-button\n"
                             "{\n"
                             "    text-align: center;\n"
                             "    spacing: 1px; /* spacing between items in the tool bar */\n"
                             "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
                             "}\n"
                             "\n"
                             "QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
                             "{\n"
                             "    background: #242424;\n"
                             "}\n"
                             "\n"
                             "QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
                             "{\n"
                             "    padding: 1px -1px -1px 1px;\n"
                             "}\n"
                             "\n"
                             "QMainWindow::separator\n"
                             "{\n"
                             "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
                             "    color: white;\n"
                             "    padding-left: 4px;\n"
                             "    border: 1px solid #4c4c4c;\n"
                             "    spacing: 3px; /* spacing between items in the tool bar */\n"
                             "}\n"
                             "\n"
                             "QMainWindow::separator:hover\n"
                             "{\n"
                             "\n"
                             "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #b2b6af,\n"
                             "    stop:0.5 #b56c17 stop:1 #D1DBCB);\n"
                             "    color: white;\n"
                             "    padding-left: 4px;\n"
                             "    border: 1px solid #6c6c6c;\n"
                             "    spacing: 3px; /* spacing between items in the tool bar */\n"
                             "}\n"
                             "\n"
                             "QToolBar {\n"
                             "    border: 1px transparent #323232;\n"
                             "    background: 1px solid #323232;\n"
                             "}\n"
                             "\n"
                             "QToolBar::handle\n"
                             "{\n"
                             "     spacing: 3px; /* spacing between items in the tool bar */\n"
                             "     background: url(:/images/handle.png);\n"
                             "}\n"
                             "\n"
                             "QMenu::separator\n"
                             "{\n"
                             "    height: 2px;\n"
                             "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
                             "    color: white;\n"
                             "    padding-left: 4px;\n"
                             "    margin-left: 10px;\n"
                             "    margin-right: 5px;\n"
                             "}\n"
                             "\n"
                             "QProgressBar\n"
                             "{\n"
                             "    border: 2px solid grey;\n"
                             "    border-radius: 5px;\n"
                             "    text-align: center;\n"
                             "}\n"
                             "\n"
                             "QProgressBar::chunk\n"
                             "{\n"
                             "    background-color: #b2b6af;\n"
                             "    width: 2.15px;\n"
                             "    margin: 0.5px;\n"
                             "}\n"
                             "\n"
                             "QTabBar::tab {\n"
                             "    color: #b1b1b1;\n"
                             "    border: 1px solid #444;\n"
                             "    border-bottom-style: none;\n"
                             "    background-color: #323232;\n"
                             "    padding-left: 10px;\n"
                             "    padding-right: 10px;\n"
                             "    padding-top: 3px;\n"
                             "    padding-bottom: 2px;\n"
                             "    margin-right: -1px;\n"
                             "}\n"
                             "\n"
                             "QTabWidget::pane {\n"
                             "    border: 1px solid #444;\n"
                             "    top: 1px;\n"
                             "}\n"
                             "\n"
                             "QTabBar::tab:last\n"
                             "{\n"
                             "    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
                             "    border-top-right-radius: 3px;\n"
                             "}\n"
                             "\n"
                             "QTabBar::tab:first:!selected\n"
                             "{\n"
                             " margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
                             "\n"
                             "\n"
                             "    border-top-left-radius: 3px;\n"
                             "}\n"
                             "\n"
                             "QTabBar::tab:!selected\n"
                             "{\n"
                             "    color: #b1b1b1;\n"
                             "    border-bottom-style: solid;\n"
                             "    margin-top: 3px;\n"
                             "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);\n"
                             "}\n"
                             "\n"
                             "QTabBar::tab:selected\n"
                             "{\n"
                             "    border-top-left-radius: 3px;\n"
                             "    border-top-right-radius: 3px;\n"
                             "    margin-bottom: 0px;\n"
                             "}\n"
                             "\n"
                             "QTabBar::tab:!selected:hover\n"
                             "{\n"
                             "    /*border-top: 2px solid #fdf6e3;\n"
                             "    padding-bottom: 3px;*/\n"
                             "    border-top-left-radius: 3px;\n"
                             "    border-top-right-radius: 3px;\n"
                             "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #fdf6e3);\n"
                             "}\n"
                             "\n"
                             "QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
                             "    color: #b1b1b1;\n"
                             "    background-color: #323232;\n"
                             "    border: 1px solid #b1b1b1;\n"
                             "    border-radius: 6px;\n"
                             "}\n"
                             "\n"
                             "QRadioButton::indicator:checked\n"
                             "{\n"
                             "    background-color: qradialgradient(\n"
                             "        cx: 0.5, cy: 0.5,\n"
                             "        fx: 0.5, fy: 0.5,\n"
                             "        radius: 1.0,\n"
                             "        stop: 0.25 #fdf6e3,\n"
                             "        stop: 0.3 #323232\n"
                             "    );\n"
                             "}\n"
                             "\n"
                             "QCheckBox::indicator{\n"
                             "    color: #b1b1b1;\n"
                             "    background-color: #323232;\n"
                             "    border: 1px solid #b1b1b1;\n"
                             "    width: 9px;\n"
                             "    height: 9px;\n"
                             "}\n"
                             "\n"
                             "QRadioButton::indicator\n"
                             "{\n"
                             "    border-radius: 6px;\n"
                             "}\n"
                             "\n"
                             "QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
                             "{\n"
                             "    border: 1px solid #fdf6e3;\n"
                             "}\n"
                             "\n"
                             "QCheckBox::indicator:checked\n"
                             "{\n"
                             "    image:url(:/images/checkbox.png);\n"
                             "}\n"
                             "\n"
                             "QCheckBox::indicator:disabled, QRadioButton::indicator:disabled\n"
                             "{\n"
                             "    border: 1px solid #444;\n"
                             "}")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(380, 340, 161, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(260, 160, 41, 41))
        self.label_19.setText("")
        self.label_19.setTextFormat(QtCore.Qt.RichText)
        self.label_19.setPixmap(QtGui.QPixmap("../images/Arrow.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(300, 10, 241, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 221, 281))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Client_Locality = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.Client_Locality.setObjectName("Client_Locality")
        self.gridLayout_2.addWidget(self.Client_Locality, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.Client_Country = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.Client_Country.setObjectName("Client_Country")
        self.gridLayout_2.addWidget(self.Client_Country, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 7, 0, 1, 1)
        self.Client_State = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.Client_State.setObjectName("Client_State")
        self.gridLayout_2.addWidget(self.Client_State, 1, 1, 1, 1)
        self.Client_CommonName = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.Client_CommonName.setObjectName("Client_CommonName")
        self.gridLayout_2.addWidget(self.Client_CommonName, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 8, 0, 1, 1)
        self.Client_NotAfter = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.Client_NotAfter.setObjectName("Client_NotAfter")
        self.gridLayout_2.addWidget(self.Client_NotAfter, 8, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        self.Client_NotBefore = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.Client_NotBefore.setObjectName("Client_NotBefore")
        self.gridLayout_2.addWidget(self.Client_NotBefore, 7, 1, 1, 1)
        self.Client_OrganizationUnit = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.Client_OrganizationUnit.setObjectName("Client_OrganizationUnit")
        self.gridLayout_2.addWidget(self.Client_OrganizationUnit, 4, 1, 1, 1)
        self.Client_Email = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.Client_Email.setObjectName("Client_Email")
        self.gridLayout_2.addWidget(self.Client_Email, 6, 1, 1, 1)
        self.Client_Organization = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.Client_Organization.setObjectName("Client_Organization")
        self.gridLayout_2.addWidget(self.Client_Organization, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 3, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 241, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 221, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 8, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.CA_OrganizationUnit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.CA_OrganizationUnit.setObjectName("CA_OrganizationUnit")
        self.gridLayout.addWidget(self.CA_OrganizationUnit, 4, 1, 1, 1)
        self.CA_NotBefore = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.CA_NotBefore.setObjectName("CA_NotBefore")
        self.gridLayout.addWidget(self.CA_NotBefore, 7, 1, 1, 1)
        self.CA_Locality = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.CA_Locality.setObjectName("CA_Locality")
        self.gridLayout.addWidget(self.CA_Locality, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.CA_NotAfter = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.CA_NotAfter.setObjectName("CA_NotAfter")
        self.gridLayout.addWidget(self.CA_NotAfter, 8, 1, 1, 1)
        self.CA_CommonName = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.CA_CommonName.setObjectName("CA_CommonName")
        self.gridLayout.addWidget(self.CA_CommonName, 5, 1, 1, 1)
        self.CA_Email = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.CA_Email.setObjectName("CA_Email")
        self.gridLayout.addWidget(self.CA_Email, 6, 1, 1, 1)
        self.CA_country = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.CA_country.setObjectName("CA_country")
        self.gridLayout.addWidget(self.CA_country, 0, 1, 1, 1)
        self.CA_State = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.CA_State.setObjectName("CA_State")
        self.gridLayout.addWidget(self.CA_State, 1, 1, 1, 1)
        self.CA_Organization = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.CA_Organization.setObjectName("CA_Organization")
        self.gridLayout.addWidget(self.CA_Organization, 3, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject)  # type: ignore

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select chain"))
        self.groupBox_2.setTitle(_translate("Dialog", "Client"))
        self.label_9.setText(_translate("Dialog", "Locality"))
        self.label_10.setText(_translate("Dialog", "Not Before"))
        self.label_8.setText(_translate("Dialog", "State"))
        self.label_13.setText(_translate("Dialog", "Common Name"))
        self.label_14.setText(_translate("Dialog", "Country"))
        self.label_16.setText(_translate("Dialog", "Not After"))
        self.label_12.setText(_translate("Dialog", "Email"))
        self.label_11.setText(_translate("Dialog", "Organization Unit"))
        self.label_18.setText(_translate("Dialog", "Organization"))
        self.groupBox.setTitle(_translate("Dialog", "CA"))
        self.label_7.setText(_translate("Dialog", "Not Before"))
        self.label_3.setText(_translate("Dialog", "Locality"))
        self.label_6.setText(_translate("Dialog", "Email"))
        self.label_15.setText(_translate("Dialog", "Not After"))
        self.label_2.setText(_translate("Dialog", "State"))
        self.label_5.setText(_translate("Dialog", "Common Name"))
        self.label_4.setText(_translate("Dialog", "Organization Unit"))
        self.label.setText(_translate("Dialog", "Country"))
        self.label_17.setText(_translate("Dialog", "Organization"))
